name: ci

on:
  push:
    paths:
      - '*.go'
      - go.mod
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Test
        run: go test -v .

      - name: Build
        run: go build -o count -v .

      - uses: actions/upload-artifact@v3
        with:
          name: count_build
          path: count

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build

    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: count_build

      - uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-west-1'
          function_name: count
          source: count
